### Overview

Extraction of survival data of SCAN-B NextSeq samples for survival analysis

In [1]:
import pandas as pd
import numpy as np

### 1. Extract survival data of SCAN-B NextSeq samples

In [2]:
# import clinical metadata of scan-b nextseq samples
metadata_nextseq = pd.read_csv("C:/Users/User/Documents/master_thesis_project_analysis/datasets/SCANB_GSE202203/scanb_uncleaned_data/GSE202203_GPL18573_Nextseq_series_matrix_metadata.txt", skiprows=38, sep='\t').transpose()

In [3]:
metadata_nextseq.head(3)

,0,1,2,3,4,5,6,7,8,9,...,56,57,58,59,60,61,62,63,64,65
!Sample_title,!Sample_geo_accession,!Sample_status,!Sample_submission_date,!Sample_last_update_date,!Sample_type,!Sample_channel_count,!Sample_source_name_ch1,!Sample_organism_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,...,!Sample_data_row_count,!Sample_instrument_model,!Sample_library_selection,!Sample_library_source,!Sample_library_strategy,!Sample_relation,!Sample_supplementary_file_1,!series_matrix_table_begin,ID_REF,!series_matrix_table_end
S000008,GSM6103034,Public on May 09 2022,May 04 2022,May 09 2022,SRA,1,Primary breast tumor,Homo sapiens,scanb external id: Q009012.C009079.S000008.l.r...,age at diagnosis: 40,...,0,Illumina NextSeq 500,cDNA,transcriptomic,RNA-Seq,Reanalysis of: GSM2530350,NONE,NaN,GSM6103034,NaN
S000019,GSM6103041,Public on May 09 2022,May 04 2022,May 09 2022,SRA,1,Primary breast tumor,Homo sapiens,scanb external id: Q009021.C009068.S000019.l.r...,age at diagnosis: 51,...,0,Illumina NextSeq 500,cDNA,transcriptomic,RNA-Seq,Reanalysis of: GSM2530351,NONE,NaN,GSM6103041,NaN

In [4]:
# make row 0 as the column name
metadata_nextseq_copy = metadata_nextseq.copy()
metadata_nextseq_copy.columns = metadata_nextseq_copy.iloc[0]

# exclude row 0 (duplicate of the column name)
metadata_nextseq_copy = metadata_nextseq_copy.iloc[1:,:]
metadata_nextseq_copy.head(3)

!Sample_title,!Sample_geo_accession,!Sample_status,!Sample_submission_date,!Sample_last_update_date,!Sample_type,!Sample_channel_count,!Sample_source_name_ch1,!Sample_organism_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,...,!Sample_data_row_count,!Sample_instrument_model,!Sample_library_selection,!Sample_library_source,!Sample_library_strategy,!Sample_relation,!Sample_supplementary_file_1,!series_matrix_table_begin,ID_REF,!series_matrix_table_end
S000008,GSM6103034,Public on May 09 2022,May 04 2022,May 09 2022,SRA,1,Primary breast tumor,Homo sapiens,scanb external id: Q009012.C009079.S000008.l.r...,age at diagnosis: 40,...,0,Illumina NextSeq 500,cDNA,transcriptomic,RNA-Seq,Reanalysis of: GSM2530350,NONE,NaN,GSM6103034,NaN
S000019,GSM6103041,Public on May 09 2022,May 04 2022,May 09 2022,SRA,1,Primary breast tumor,Homo sapiens,scanb external id: Q009021.C009068.S000019.l.r...,age at diagnosis: 51,...,0,Illumina NextSeq 500,cDNA,transcriptomic,RNA-Seq,Reanalysis of: GSM2530351,NONE,NaN,GSM6103041,NaN
S000028,GSM6103048,Public on May 09 2022,May 04 2022,May 09 2022,SRA,1,Primary breast tumor,Homo sapiens,scanb external id: Q009015.C009059.S000028.l.r...,age at diagnosis: 45,...,0,Illumina NextSeq 500,cDNA,transcriptomic,RNA-Seq,Reanalysis of: GSM2530048,NONE,NaN,GSM6103048,NaN

In [5]:
# extract patient characteristics columns
nextseq_patient_char = metadata_nextseq_copy.loc[:, ['!Sample_characteristics_ch1']]
nextseq_patient_char.head(3)

!Sample_title,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,...,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1
S000008,scanb external id: Q009012.C009079.S000008.l.r...,age at diagnosis: 40,tumor size: 9,lymph node group: N0,lymph node status: NodeNegative,er status: 1,pgr status: 1,her2 status: 0,ki67 status: NA,nhg: G2,...,endocrine treated: 1,chemo treated: 0,overall survival days: 3165,overall survival years: 8.6652977412731,overall survival event: 0,relapse free interval days: 534,relapse free interval years: 1.46201232032854,relapse free interval event: 1,esr1 expression: log2(tpm+0.1): 5.97571076375966,esr2 expression: log2(tpm+0.1): -3.32192809488736
S000019,scanb external id: Q009021.C009068.S000019.l.r...,age at diagnosis: 51,tumor size: 32,lymph node group: N0,lymph node status: NodeNegative,er status: 1,pgr status: 1,her2 status: NA,ki67 status: NA,nhg: G3,...,endocrine treated: 1,chemo treated: 1,overall survival days: 3165,overall survival years: 8.6652977412731,overall survival event: 0,relapse free interval days: 490,relapse free interval years: 1.34154688569473,relapse free interval event: 0,esr1 expression: log2(tpm+0.1): 7.54301496177958,esr2 expression: log2(tpm+0.1): -0.80285905272...
S000028,scanb external id: Q009015.C009059.S000028.l.r...,age at diagnosis: 45,tumor size: 25,lymph node group: N0,lymph node status: 4toX,er status: 1,pgr status: 1,her2 status: 0,ki67 status: NA,nhg: G3,...,endocrine treated: 1,chemo treated: 1,overall survival days: 3158,overall survival years: 8.64613278576318,overall survival event: 0,relapse free interval days: 387,relapse free interval years: 1.05954825462012,relapse free interval event: 0,esr1 expression: log2(tpm+0.1): 7.05444629578434,esr2 expression: log2(tpm+0.1): -1.64909758986146

In [6]:
# extract survival days, years and events that are in columns 15, 16 and 17
nextseq_survival = nextseq_patient_char.iloc[:,[15, 16, 17]]
nextseq_survival.head(3)

!Sample_title,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1
S000008,overall survival days: 3165,overall survival years: 8.6652977412731,overall survival event: 0
S000019,overall survival days: 3165,overall survival years: 8.6652977412731,overall survival event: 0
S000028,overall survival days: 3158,overall survival years: 8.64613278576318,overall survival event: 0

In [7]:
# rename column names
nextseq_survival.columns = ['overall_survival_days', 'overall_survival_years', 'overall_survival_event']
nextseq_survival.head(3)

,overall_survival_days,overall_survival_years,overall_survival_event
S000008,overall survival days: 3165,overall survival years: 8.6652977412731,overall survival event: 0
S000019,overall survival days: 3165,overall survival years: 8.6652977412731,overall survival event: 0
S000028,overall survival days: 3158,overall survival years: 8.64613278576318,overall survival event: 0

### 2. Convert survival data into suitable format

In [8]:
# function to keep only numbers in the survival data
def keep_numbers_in_survival(df, col_names):
    df_copy = df.copy()
    df_nrow = df_copy.shape[0]
    for col in col_names:
        for i in range(df_nrow):
            value = df_copy.loc[df_copy.index[i], col]
            df_copy.loc[df_copy.index[i], col] = value.split(': ')[1]

    return df_copy

In [9]:
# keep only the numeric data
nextseq_survival_modified = keep_numbers_in_survival(nextseq_survival, nextseq_survival.columns.tolist())
nextseq_survival_modified.head(3)

        overall_survival_days overall_survival_years overall_survival_event
S000008                  3165        8.6652977412731                      0
S000019                  3165        8.6652977412731                      0
S000028                  3158       8.64613278576318                      0

In [10]:
nextseq_survival_modified.shape

(294, 3)

In [11]:
# convert data types
nextseq_survival_modified['overall_survival_event'] = pd.to_numeric(nextseq_survival_modified['overall_survival_event'], errors ='coerce').astype('Int64')
nextseq_survival_modified['overall_survival_days'] = pd.to_numeric(nextseq_survival_modified['overall_survival_days'], errors ='coerce').astype('Int64')
nextseq_survival_modified['overall_survival_years'] = pd.to_numeric(nextseq_survival_modified['overall_survival_years'], errors ='coerce').astype('Float64')

In [12]:
nextseq_survival_modified.head(3)

         overall_survival_days  overall_survival_years  overall_survival_event
S000008                   3165                8.665298                       0
S000019                   3165                8.665298                       0
S000028                   3158                8.646133                       0

In [13]:
# check data types
nextseq_survival_modified.dtypes

overall_survival_days       Int64
overall_survival_years    Float64
overall_survival_event      Int64
dtype: object

In [14]:
# check the proportion of survival events
nextseq_survival_modified['overall_survival_event'].value_counts()

overall_survival_event
0    253
1     41
Name: count, dtype: Int64

In [15]:
# check for missing values
nextseq_survival_modified.isna().sum(axis=0)

overall_survival_days     0
overall_survival_years    0
overall_survival_event    0
dtype: int64

In [16]:
# round the overall_survival_years to 3 decimal places
nextseq_survival_modified.loc[:,'overall_survival_years'] = round(nextseq_survival_modified['overall_survival_years'],3)
nextseq_survival_modified.head(3)

         overall_survival_days  overall_survival_years  overall_survival_event
S000008                   3165                   8.665                       0
S000019                   3165                   8.665                       0
S000028                   3158                   8.646                       0

In [28]:
# get maximum overall survival years in the whole dataset (including normal-like and unclassified samples)
nextseq_survival_modified.loc[nextseq_survival_modified['overall_survival_years'].idxmax(),'overall_survival_years']

8.665

### 2. Extract survival data of selected SCAN-B NextSeq samples 

These samples include only the four major breast cancer subtypes (Basal, HER2, LumA, LumB)

In [25]:
# import scanb nextseq dataset
scanb_nextseq = pd.read_csv("C:/Users/User/Documents/master_thesis_project_analysis/datasets/SCANB_GSE202203/scanb_cleaned_data/pam50genes_raw_counts_subtype_scanb_nextseq.csv", 
                          header=0, index_col=0)

In [26]:
print(scanb_nextseq.shape)

(276, 51)

In [29]:
# extract only selected nextseq samples (excluding normal-like and unclassified) from the survival dataset
nextseq_selected_survival = nextseq_survival_modified.loc[nextseq_survival_modified.index.isin(scanb_nextseq.index),:]
print(nextseq_selected_survival.shape)

(276, 3)

In [30]:
print(nextseq_selected_survival['overall_survival_event'].value_counts())

overall_survival_event
0    237
1     39
Name: count, dtype: Int64

In [35]:
# get maximum overall survival years
nextseq_selected_survival.loc[nextseq_selected_survival['overall_survival_years'].idxmax(),'overall_survival_years']

8.665

In [31]:
# select only the rows from gene expression_subtype dataset that are in survival dataset
# reorder the rows in the gene expression_subtype dataset according to the survival dataset
scanb_nextseq_sorted = scanb_nextseq.loc[nextseq_selected_survival.index,:]
print(scanb_nextseq_sorted.shape)

(276, 51)

In [32]:
print(scanb_nextseq_sorted.index.equals(nextseq_selected_survival.index))

True

### 3. Merge survival data with subtype labels

In [34]:
# merge survival data of selected nextseq samples with subtype labels
nextseq_survival_subtype = nextseq_selected_survival.join(scanb_nextseq_sorted.loc[:,'subtype'])
print(nextseq_survival_subtype.shape)

(276, 4)

In [33]:
# # save file
# nextseq_survival_subtype.to_csv('scanb_nextseq_survival_subtype.csv')