### Overview

Cleaning and organization of SCAN-B HiSeq and NSCAN-B NextSeq raw counts dataset

In [1]:
import pandas as pd
import numpy as np

### 1. Prepare the SCAN-B raw count matrix
Clean the raw count matrix, such that the column names are genes and row names are samples.

In [2]:
# import raw counts
raw_counts = pd.read_csv("C:/Users/User/Documents/master_thesis_project_analysis/datasets/SCANB_GSE202203/scanb_uncleaned_data/GSE202203_RawCounts_gene_3207.tsv", sep='\t')

In [3]:
# view the first three rows 
raw_counts.head(3)

,X,S000001,S000002,S000003,S000006,S000008,S000011,S000012,S000013,S000014,...,S006771,S006775,S006776,S006777,S006778,S006780,S006781,S006782,S006783,S006786
0,A1BG,412.358202,105.952180,157.582677,104.325878,145.012995,201.812885,289.173348,23.331057,315.553515,...,277.598262,200.229453,338.885008,156.742869,929.850405,833.107618,456.665675,298.198671,240.898731,533.324431
1,A1CF,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,A2M,23884.926531,7526.736567,30855.152448,36483.893945,17015.951039,23280.069420,10460.446135,29668.790548,28683.983679,...,46627.183753,77490.038656,25603.416998,43521.209883,37932.736496,19976.140792,16323.512258,38746.420729,60812.177742,25998.981476

In [4]:
# transpose the raw counts (genes = row names --> column names, samples = column names --> row names)
raw_counts = raw_counts.transpose()

In [5]:
# view the first three rows
raw_counts.head(3)

,0,1,2,3,4,5,6,7,8,9,...,19634,19635,19636,19637,19638,19639,19640,19641,19642,19643
X,A1BG,A1CF,A2M,A2ML1,A3GALT2,A4GALT,A4GNT,AAAS,AACS,AADAC,...,ZWILCH,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1,ZZZ3
S000001,412.358202,0.0,23884.926531,1.426652,0.0,2836.330202,0.0,976.445204,2161.033619,0.0,...,308.9017,225.6337,224.1467,644.9333,533.6666,16.48217,1238.535,6349.836,2238.879,785.94
S000002,105.95218,0.0,7526.736567,404.546684,0.0,274.625857,0.0,378.742855,564.993344,13.133329,...,347.9658,594.7327,128.46,305.5,252.9467,27.5067,609.9401,3799.82,704.5869,756.4233

In [6]:
# make row 0 as the column names 
raw_counts.columns = raw_counts.iloc[0]

# exclude row 0 (duplicate of the column names)
raw_counts = raw_counts.iloc[1:,:]

In [7]:
# view the first three rows
raw_counts.head(3)

X,A1BG,A1CF,A2M,A2ML1,A3GALT2,A4GALT,A4GNT,AAAS,AACS,AADAC,...,ZWILCH,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1,ZZZ3
S000001,412.358202,0.0,23884.926531,1.426652,0.0,2836.330202,0.0,976.445204,2161.033619,0.0,...,308.9017,225.6337,224.1467,644.9333,533.6666,16.48217,1238.535,6349.836,2238.879,785.94
S000002,105.95218,0.0,7526.736567,404.546684,0.0,274.625857,0.0,378.742855,564.993344,13.133329,...,347.9658,594.7327,128.46,305.5,252.9467,27.5067,609.9401,3799.82,704.5869,756.4233
S000003,157.582677,0.0,30855.152448,163.826684,0.0,549.653372,0.0,1198.252831,2299.233003,1.426657,...,378.5762,765.1066,200.7533,455.0467,734.6801,74.74185,1199.876,12945.19,1972.74,1076.733

In [8]:
# check the dimensions
raw_counts.shape

(3207, 19644)

In [9]:
# check the sum of all the rows in the raw counts
raw_counts.sum(axis=1)

S000001    29249860.821923
S000002    11993762.901302
S000003    31867366.564577
S000006    28830557.057803
S000008    16610231.335964
                ...
S006780    51602008.308198
S006781    42209284.998493
S006782    47072956.049193
S006783    41630424.023148
S006786    45362319.586861
Length: 3207, dtype: object

### 2. Keep PAM50 genes in the raw count matrix

In [48]:
# import PAM50 genes
pam50 = pd.read_csv("C:/Users/User/Documents/master_thesis_project_analysis/datasets/pam50gene_list_csv.csv", header=0)
pam50

   old_gene_symbol new_gene_symbol  ensembl_gene_id
0           ACTR3B          ACTR3B  ENSG00000133627
1             ANLN            ANLN  ENSG00000011426
2             BAG1            BAG1  ENSG00000107262
3             BCL2            BCL2  ENSG00000171791
4            BIRC5           BIRC5  ENSG00000089685
5            BLVRA           BLVRA  ENSG00000106605
6            CCNB1           CCNB1  ENSG00000134057
7            CCNE1           CCNE1  ENSG00000105173
8            CDC20           CDC20  ENSG00000117399
9             CDC6            CDC6  ENSG00000094804
10           CDCA1            NUF2  ENSG00000143228
11            CDH3            CDH3  ENSG00000062038
12           CENPF           CENPF  ENSG00000117724
13           CEP55           CEP55  ENSG00000138180
14           CXXC5           CXXC5  ENSG00000171604
15            EGFR            EGFR  ENSG00000146648
16           ERBB2           ERBB2  ENSG00000141736
17            ESR1            ESR1  ENSG00000091831
18            EXO1            EXO1  ENSG00000174371
19           FGFR4           FGFR4  ENSG00000160867
20           FOXA1           FOXA1  ENSG00000129514
21           FOXC1           FOXC1  ENSG00000054598
22          GPR160          GPR160  ENSG00000173890
23            GRB7            GRB7  ENSG00000141738
24           KIF2C           KIF2C  ENSG00000142945
25           KNTC2           NDC80  ENSG00000080986
26           KRT14           KRT14  ENSG00000186847
27           KRT17           KRT17  ENSG00000128422
28            KRT5            KRT5  ENSG00000186081
29            MAPT            MAPT  ENSG00000186868
30            MDM2            MDM2  ENSG00000135679
31            MELK            MELK  ENSG00000165304
32             MIA             MIA  ENSG00000261857
33           MKI67           MKI67  ENSG00000148773
34            MLPH            MLPH  ENSG00000115648
35           MMP11           MMP11  ENSG00000099953
36           MYBL2           MYBL2  ENSG00000101057
37             MYC             MYC  ENSG00000136997
38            NAT1            NAT1  ENSG00000171428
39           ORC6L            ORC6  ENSG00000091651
40             PGR             PGR  ENSG00000082175
41           PHGDH           PHGDH  ENSG00000092621
42           PTTG1           PTTG1  ENSG00000164611
43            RRM2            RRM2  ENSG00000171848
44           SFRP1           SFRP1  ENSG00000104332
45         SLC39A6         SLC39A6  ENSG00000141424
46         TMEM45B         TMEM45B  ENSG00000151715
47            TYMS            TYMS  ENSG00000176890
48           UBE2C           UBE2C  ENSG00000175063
49           UBE2T           UBE2T  ENSG00000077152

In [49]:
# check whether PAM50 genes are in the raw counts
raw_counts.loc[:, raw_counts.columns.isin(pam50['new_gene_symbol'].tolist())].shape

(3207, 50)

In [50]:
# keep only PAM50 genes in the raw counts
raw_counts_pam50 = raw_counts.loc[:, raw_counts.columns.isin(pam50['new_gene_symbol'].tolist())]
raw_counts_pam50.shape

(3207, 50)

In [51]:
# check the first three rows
raw_counts_pam50.head(3)

X,ACTR3B,ANLN,BAG1,BCL2,BIRC5,BLVRA,CCNB1,CCNE1,CDC20,CDC6,...,PGR,PHGDH,PTTG1,RRM2,SFRP1,SLC39A6,TMEM45B,TYMS,UBE2C,UBE2T
S000001,152.799996,129.138954,2947.446735,3038.400354,165.67999,2951.49956,209.786,16.78077,125.9733,137.6133,...,15050.89,1203.915,92.14667,212.8533,382.24,43926.99,1855.573,356.1333,81.97333,93.61333
S000002,382.55334,1304.234024,283.470164,311.269085,1060.020696,426.106653,848.9675,56.03837,2552.327,445.0957,...,97.68009,3789.946,526.4949,1437.789,9125.912,4558.062,11.3674,922.5678,806.667,409.3733
S000003,224.104476,1791.228363,1587.052535,545.710179,708.487149,2391.738217,1491.881,76.77382,1006.367,414.0641,...,223.3733,1890.669,613.953,1002.494,3267.987,8808.301,2396.193,673.6553,723.492,479.0

In [52]:
# check whether the gene order is the same
raw_counts_pam50.columns.tolist() == pam50['new_gene_symbol'].tolist()

False

In [53]:
# rearrange the columns
raw_counts_pam50 = raw_counts_pam50[pam50['new_gene_symbol'].tolist()]
raw_counts_pam50.shape

(3207, 50)

In [55]:
raw_counts_pam50.head(3)

X,ACTR3B,ANLN,BAG1,BCL2,BIRC5,BLVRA,CCNB1,CCNE1,CDC20,CDC6,...,PGR,PHGDH,PTTG1,RRM2,SFRP1,SLC39A6,TMEM45B,TYMS,UBE2C,UBE2T
S000001,152.799996,129.138954,2947.446735,3038.400354,165.67999,2951.49956,209.786,16.78077,125.9733,137.6133,...,15050.89,1203.915,92.14667,212.8533,382.24,43926.99,1855.573,356.1333,81.97333,93.61333
S000002,382.55334,1304.234024,283.470164,311.269085,1060.020696,426.106653,848.9675,56.03837,2552.327,445.0957,...,97.68009,3789.946,526.4949,1437.789,9125.912,4558.062,11.3674,922.5678,806.667,409.3733
S000003,224.104476,1791.228363,1587.052535,545.710179,708.487149,2391.738217,1491.881,76.77382,1006.367,414.0641,...,223.3733,1890.669,613.953,1002.494,3267.987,8808.301,2396.193,673.6553,723.492,479.0

In [56]:
# check whether the gene order is the same after rearranging the columns
raw_counts_pam50.columns.tolist() == pam50['new_gene_symbol'].tolist()

True

In [57]:
# rename the columns to be ensemble gene ids
raw_counts_pam50.columns = pam50['ensembl_gene_id'].tolist()
raw_counts_pam50.head(3)

,ENSG00000133627,ENSG00000011426,ENSG00000107262,ENSG00000171791,ENSG00000089685,ENSG00000106605,ENSG00000134057,ENSG00000105173,ENSG00000117399,ENSG00000094804,...,ENSG00000082175,ENSG00000092621,ENSG00000164611,ENSG00000171848,ENSG00000104332,ENSG00000141424,ENSG00000151715,ENSG00000176890,ENSG00000175063,ENSG00000077152
S000001,152.799996,129.138954,2947.446735,3038.400354,165.67999,2951.49956,209.786,16.78077,125.9733,137.6133,...,15050.89,1203.915,92.14667,212.8533,382.24,43926.99,1855.573,356.1333,81.97333,93.61333
S000002,382.55334,1304.234024,283.470164,311.269085,1060.020696,426.106653,848.9675,56.03837,2552.327,445.0957,...,97.68009,3789.946,526.4949,1437.789,9125.912,4558.062,11.3674,922.5678,806.667,409.3733
S000003,224.104476,1791.228363,1587.052535,545.710179,708.487149,2391.738217,1491.881,76.77382,1006.367,414.0641,...,223.3733,1890.669,613.953,1002.494,3267.987,8808.301,2396.193,673.6553,723.492,479.0

In [58]:
# convert raw data to integers because deseq2 normalization accepts raw counts as inputs and TCGA has integers too
raw_counts_pam50 = raw_counts_pam50.round().astype('int')

In [59]:
# check the first three rows
raw_counts_pam50.head(3)

,ENSG00000133627,ENSG00000011426,ENSG00000107262,ENSG00000171791,ENSG00000089685,ENSG00000106605,ENSG00000134057,ENSG00000105173,ENSG00000117399,ENSG00000094804,...,ENSG00000082175,ENSG00000092621,ENSG00000164611,ENSG00000171848,ENSG00000104332,ENSG00000141424,ENSG00000151715,ENSG00000176890,ENSG00000175063,ENSG00000077152
S000001,152,129,2947,3038,165,2951,209,16,125,137,...,15050,1203,92,212,382,43926,1855,356,81,93
S000002,382,1304,283,311,1060,426,848,56,2552,445,...,97,3789,526,1437,9125,4558,11,922,806,409
S000003,224,1791,1587,545,708,2391,1491,76,1006,414,...,223,1890,613,1002,3267,8808,2396,673,723,479

### 3. Extract SCAN-B HiSeq samples and their subtype labels

In [60]:
# import metadata of scan-b hiseq samples annd transpose it
metadata_hiseq = pd.read_csv("C:/Users/User/Documents/master_thesis_project_analysis/datasets/SCANB_GSE202203/scanb_uncleaned_data/GSE202203_GPL11154_HiSeq_series_matrix_metadata.txt", skiprows=38, sep='\t').transpose()

In [61]:
# check the dimensions 
metadata_hiseq.shape

(2914, 66)

In [62]:
# check the first three rows
metadata_hiseq.head(3)

,0,1,2,3,4,5,6,7,8,9,...,56,57,58,59,60,61,62,63,64,65
!Sample_title,!Sample_geo_accession,!Sample_status,!Sample_submission_date,!Sample_last_update_date,!Sample_type,!Sample_channel_count,!Sample_source_name_ch1,!Sample_organism_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,...,!Sample_data_row_count,!Sample_instrument_model,!Sample_library_selection,!Sample_library_source,!Sample_library_strategy,!Sample_relation,!Sample_supplementary_file_1,!series_matrix_table_begin,ID_REF,!series_matrix_table_end
S000001,GSM6103030,Public on May 09 2022,May 04 2022,May 09 2022,SRA,1,Primary breast tumor,Homo sapiens,scanb external id: Q009061.C009086.S000001.l.r...,age at diagnosis: 85,...,0,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,Reanalysis of: GSM2530698,NONE,NaN,GSM6103030,NaN
S000002,GSM6103031,Public on May 09 2022,May 04 2022,May 09 2022,SRA,1,Primary breast tumor,Homo sapiens,scanb external id: Q009043.C009085.S000002.l.r...,age at diagnosis: 66,...,0,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,Reanalysis of: GSM2530699,NONE,NaN,GSM6103031,NaN

In [63]:
# make row 0 as the column name
metadata_hiseq_copy = metadata_hiseq.copy()
metadata_hiseq_copy.columns = metadata_hiseq_copy.iloc[0]

# exclude row 0 (duplicate of the column names)
metadata_hiseq_copy = metadata_hiseq_copy.iloc[1:,:]
metadata_hiseq_copy.head(3)

!Sample_title,!Sample_geo_accession,!Sample_status,!Sample_submission_date,!Sample_last_update_date,!Sample_type,!Sample_channel_count,!Sample_source_name_ch1,!Sample_organism_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,...,!Sample_data_row_count,!Sample_instrument_model,!Sample_library_selection,!Sample_library_source,!Sample_library_strategy,!Sample_relation,!Sample_supplementary_file_1,!series_matrix_table_begin,ID_REF,!series_matrix_table_end
S000001,GSM6103030,Public on May 09 2022,May 04 2022,May 09 2022,SRA,1,Primary breast tumor,Homo sapiens,scanb external id: Q009061.C009086.S000001.l.r...,age at diagnosis: 85,...,0,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,Reanalysis of: GSM2530698,NONE,NaN,GSM6103030,NaN
S000002,GSM6103031,Public on May 09 2022,May 04 2022,May 09 2022,SRA,1,Primary breast tumor,Homo sapiens,scanb external id: Q009043.C009085.S000002.l.r...,age at diagnosis: 66,...,0,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,Reanalysis of: GSM2530699,NONE,NaN,GSM6103031,NaN
S000003,GSM6103032,Public on May 09 2022,May 04 2022,May 09 2022,SRA,1,Primary breast tumor,Homo sapiens,scanb external id: Q009039.C009084.S000003.l.r...,age at diagnosis: 63,...,0,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,Reanalysis of: GSM2530710,NONE,NaN,GSM6103032,NaN

In [64]:
# check the dimensions
metadata_hiseq_copy.shape

(2913, 66)

In [65]:
# extract the subtype column
hiseq_subtype = metadata_hiseq_copy.iloc[:,[18]]
hiseq_subtype.columns = ['subtype']
hiseq_subtype.head(3)

                      subtype
S000001   pam50 subtype: LumA
S000002  pam50 subtype: Basal
S000003   pam50 subtype: HER2

In [66]:
# check the subtype proportion
hiseq_subtype.value_counts()

subtype
pam50 subtype: LumA            1398
pam50 subtype: LumB             818
pam50 subtype: Basal            288
pam50 subtype: HER2             251
pam50 subtype: Normal            99
pam50 subtype: Unclassified      59
Name: count, dtype: int64

In [67]:
# subset hiseq samples from the raw counts
raw_counts_pam50_hiseq = raw_counts_pam50.loc[raw_counts_pam50.index.isin(hiseq_subtype.index),:]
raw_counts_pam50_hiseq.shape

(2913, 50)

In [68]:
# check if the indices match
raw_counts_pam50_hiseq.index.equals(hiseq_subtype.index)

True

In [72]:
# check for low-quality samples (characterized by having lots of low-count genes)
# check for rows with less than 10 raw read counts in all the gene columns
# 10 is the threshold for low count genes according to DESeq2 analysis documentation
print((raw_counts_pam50_hiseq.iloc[:, 0:50] <= 10).all(axis=1).sum())

# check rows with less than 10 raw read counts in at least half of the gene columns
print(((raw_counts_pam50_hiseq.iloc[:, 0:50] <= 10).sum(axis=1) >= raw_counts_pam50_hiseq.iloc[:, 0:50].shape[1] // 2).sum())

0
0

In [33]:
# join raw counts of the samples and their corresponding subtype label
pam50_raw_counts_subtype_hiseq = raw_counts_pam50_hiseq.join(hiseq_subtype)
pam50_raw_counts_subtype_hiseq.shape

(2913, 51)

In [43]:
# remove samples (rows) that are unclassified and normal like
pam50_raw_counts_subtype_hiseq = pam50_raw_counts_subtype_hiseq.loc[(pam50_raw_counts_subtype_hiseq['subtype'] != 'pam50 subtype: Normal') &
(pam50_raw_counts_subtype_hiseq['subtype'] != 'pam50 subtype: Unclassified'),:]

# check the dimensions of the filtered dataset after removing these samples
print(pam50_raw_counts_subtype_hiseq.shape)

# check subtype proportion after removing unclassified and normal-like samples
pam50_raw_counts_subtype_hiseq['subtype'].value_counts()

(2755, 51)

subtype
LumA     1398
LumB      818
Basal     288
Her2      251
Name: count, dtype: int64

In [36]:
# relabel the classes
label_dict = {'pam50 subtype: LumA': 'LumA', 'pam50 subtype: LumB': 'LumB', 'pam50 subtype: Basal': 'Basal', 'pam50 subtype: HER2': 'Her2'}
pam50_raw_counts_subtype_hiseq['subtype'] = pam50_raw_counts_subtype_hiseq['subtype'].replace(label_dict)
pam50_raw_counts_subtype_hiseq['subtype'].value_counts()

subtype
LumA     1398
LumB      818
Basal     288
Her2      251
Name: count, dtype: int64

In [37]:
# check the first three rows
pam50_raw_counts_subtype_hiseq.head(3)

,ENSG00000133627,ENSG00000011426,ENSG00000107262,ENSG00000171791,ENSG00000089685,ENSG00000106605,ENSG00000134057,ENSG00000105173,ENSG00000117399,ENSG00000094804,...,ENSG00000092621,ENSG00000164611,ENSG00000171848,ENSG00000104332,ENSG00000141424,ENSG00000151715,ENSG00000176890,ENSG00000175063,ENSG00000077152,subtype
S000001,152,129,2947,3038,165,2951,209,16,125,137,...,1203,92,212,382,43926,1855,356,81,93,LumA
S000002,382,1304,283,311,1060,426,848,56,2552,445,...,3789,526,1437,9125,4558,11,922,806,409,Basal
S000003,224,1791,1587,545,708,2391,1491,76,1006,414,...,1890,613,1002,3267,8808,2396,673,723,479,Her2

In [38]:
# save
# pam50_raw_counts_subtype_hiseq.to_csv('pam50genes_raw_counts_subtype_scanb_hiseq.csv')

### 4. Extract SCAN-B NextSeq samples and their subtype labels

In [73]:
# import metadata of scan-b nextseq samples annd transpose it
metadata_nextseq = pd.read_csv("C:/Users/User/Documents/master_thesis_project_analysis/datasets/SCANB_GSE202203/scanb_uncleaned_data/GSE202203_GPL18573_NextSeq_series_matrix_metadata.txt", skiprows=38, sep='\t').transpose()

In [74]:
# check the dimensions
metadata_nextseq.shape

(295, 66)

In [75]:
# check the first three rows
metadata_nextseq.head(3)

,0,1,2,3,4,5,6,7,8,9,...,56,57,58,59,60,61,62,63,64,65
!Sample_title,!Sample_geo_accession,!Sample_status,!Sample_submission_date,!Sample_last_update_date,!Sample_type,!Sample_channel_count,!Sample_source_name_ch1,!Sample_organism_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,...,!Sample_data_row_count,!Sample_instrument_model,!Sample_library_selection,!Sample_library_source,!Sample_library_strategy,!Sample_relation,!Sample_supplementary_file_1,!series_matrix_table_begin,ID_REF,!series_matrix_table_end
S000008,GSM6103034,Public on May 09 2022,May 04 2022,May 09 2022,SRA,1,Primary breast tumor,Homo sapiens,scanb external id: Q009012.C009079.S000008.l.r...,age at diagnosis: 40,...,0,Illumina NextSeq 500,cDNA,transcriptomic,RNA-Seq,Reanalysis of: GSM2530350,NONE,NaN,GSM6103034,NaN
S000019,GSM6103041,Public on May 09 2022,May 04 2022,May 09 2022,SRA,1,Primary breast tumor,Homo sapiens,scanb external id: Q009021.C009068.S000019.l.r...,age at diagnosis: 51,...,0,Illumina NextSeq 500,cDNA,transcriptomic,RNA-Seq,Reanalysis of: GSM2530351,NONE,NaN,GSM6103041,NaN

In [76]:
# make row 0 as the column name
metadata_nextseq_copy = metadata_nextseq.copy()
metadata_nextseq_copy.columns = metadata_nextseq_copy.iloc[0]

# exclude row 0 (duplicated column names)
metadata_nextseq_copy = metadata_nextseq_copy.iloc[1:,:]
metadata_nextseq_copy.head(3)

!Sample_title,!Sample_geo_accession,!Sample_status,!Sample_submission_date,!Sample_last_update_date,!Sample_type,!Sample_channel_count,!Sample_source_name_ch1,!Sample_organism_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,...,!Sample_data_row_count,!Sample_instrument_model,!Sample_library_selection,!Sample_library_source,!Sample_library_strategy,!Sample_relation,!Sample_supplementary_file_1,!series_matrix_table_begin,ID_REF,!series_matrix_table_end
S000008,GSM6103034,Public on May 09 2022,May 04 2022,May 09 2022,SRA,1,Primary breast tumor,Homo sapiens,scanb external id: Q009012.C009079.S000008.l.r...,age at diagnosis: 40,...,0,Illumina NextSeq 500,cDNA,transcriptomic,RNA-Seq,Reanalysis of: GSM2530350,NONE,NaN,GSM6103034,NaN
S000019,GSM6103041,Public on May 09 2022,May 04 2022,May 09 2022,SRA,1,Primary breast tumor,Homo sapiens,scanb external id: Q009021.C009068.S000019.l.r...,age at diagnosis: 51,...,0,Illumina NextSeq 500,cDNA,transcriptomic,RNA-Seq,Reanalysis of: GSM2530351,NONE,NaN,GSM6103041,NaN
S000028,GSM6103048,Public on May 09 2022,May 04 2022,May 09 2022,SRA,1,Primary breast tumor,Homo sapiens,scanb external id: Q009015.C009059.S000028.l.r...,age at diagnosis: 45,...,0,Illumina NextSeq 500,cDNA,transcriptomic,RNA-Seq,Reanalysis of: GSM2530048,NONE,NaN,GSM6103048,NaN

In [77]:
# check the dimensions
metadata_nextseq_copy.shape

(294, 66)

In [78]:
# check subtype column
nextseq_subtype = metadata_nextseq_copy.iloc[:,[18]]
nextseq_subtype.columns = ['subtype']
nextseq_subtype.head(3)

                     subtype
S000008  pam50 subtype: LumA
S000019  pam50 subtype: LumB
S000028  pam50 subtype: LumA

In [79]:
# check subtype proportion
nextseq_subtype.value_counts()

subtype
pam50 subtype: LumA            142
pam50 subtype: LumB             78
pam50 subtype: Basal            29
pam50 subtype: HER2             27
pam50 subtype: Normal           13
pam50 subtype: Unclassified      5
Name: count, dtype: int64

In [80]:
# subset nextseq samples
raw_counts_pam50_nextseq = raw_counts_pam50.loc[raw_counts_pam50.index.isin(nextseq_subtype.index),:]
raw_counts_pam50_nextseq.shape

(294, 50)

In [81]:
# check if the indices match
raw_counts_pam50_nextseq.index.equals(nextseq_subtype.index)

True

In [82]:
# check for low-quality samples (characterized by having lots of low-count genes)
# check for rows with less than 10 raw read counts in all the gene columns
# 10 is the threshold for low count genes according to DESeq2 analysis documentation
print((raw_counts_pam50_nextseq.iloc[:, 0:50] <= 10).all(axis=1).sum())

# check rows with less than 10 raw read counts in at least half of the gene columns
print(((raw_counts_pam50_nextseq.iloc[:, 0:50] <= 10).sum(axis=1) >= raw_counts_pam50_nextseq.iloc[:, 0:50].shape[1] // 2).sum())

0
0

In [77]:
# join raw counts of the samples and their corresponding subtype label
pam50_raw_counts_subtype_nextseq = raw_counts_pam50_nextseq.join(nextseq_subtype)
pam50_raw_counts_subtype_nextseq.shape

(294, 51)

In [78]:
# remove samples (rows) that are unclassified and normal like
pam50_raw_counts_subtype_nextseq = pam50_raw_counts_subtype_nextseq.loc[(pam50_raw_counts_subtype_nextseq['subtype'] != 'pam50 subtype: Normal') &
(pam50_raw_counts_subtype_nextseq['subtype'] != 'pam50 subtype: Unclassified'),:]

# check dimensions after removing these samples
print(pam50_raw_counts_subtype_nextseq.shape)

# check subtype proportion of removing normal-like and unclassified samples
pam50_raw_counts_subtype_nextseq['subtype'].value_counts()

(276, 51)

In [80]:
# relabel the classes
label_dict = {'pam50 subtype: LumA': 'LumA', 'pam50 subtype: LumB': 'LumB', 'pam50 subtype: Basal': 'Basal', 'pam50 subtype: HER2': 'Her2'}
pam50_raw_counts_subtype_nextseq['subtype'] = pam50_raw_counts_subtype_nextseq['subtype'].replace(label_dict)
pam50_raw_counts_subtype_nextseq['subtype'].value_counts()

subtype
LumA     142
LumB      78
Basal     29
Her2      27
Name: count, dtype: int64

In [81]:
# check the first three rows
pam50_raw_counts_subtype_nextseq.head(3)

,ENSG00000133627,ENSG00000011426,ENSG00000107262,ENSG00000171791,ENSG00000089685,ENSG00000106605,ENSG00000134057,ENSG00000105173,ENSG00000117399,ENSG00000094804,...,ENSG00000092621,ENSG00000164611,ENSG00000171848,ENSG00000104332,ENSG00000141424,ENSG00000151715,ENSG00000176890,ENSG00000175063,ENSG00000077152,subtype
S000008,113,247,1425,1711,325,882,406,17,301,144,...,582,108,439,1043,33458,63,339,143,149,LumA
S000019,1093,371,711,1683,505,1287,474,80,728,448,...,673,318,826,224,14810,36,640,722,444,LumB
S000028,636,1832,2932,4047,1117,1326,1640,105,1130,432,...,485,584,2157,6367,14954,525,1097,1383,949,LumA

In [83]:
# save
# pam50_raw_counts_subtype_nextseq.to_csv('pam50genes_raw_counts_subtype_scanb_nextseq.csv')