### Overview

Extraction of survival data of SCAN-B HiSeq samples for survival analysis

In [1]:
import pandas as pd
import numpy as np

### 1. Extract survival data of SCAN-B HiSeq samples

In [2]:
# import clinical metadata of scan-b hiseq samples
metadata_hiseq = pd.read_csv("C:/Users/User/Documents/master_thesis_project_analysis/datasets/SCANB_GSE202203/scanb_uncleaned_data/GSE202203_GPL11154_HiSeq_series_matrix_metadata.txt", skiprows=38, sep='\t').transpose()

In [3]:
metadata_hiseq.head(3)

,0,1,2,3,4,5,6,7,8,9,...,56,57,58,59,60,61,62,63,64,65
!Sample_title,!Sample_geo_accession,!Sample_status,!Sample_submission_date,!Sample_last_update_date,!Sample_type,!Sample_channel_count,!Sample_source_name_ch1,!Sample_organism_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,...,!Sample_data_row_count,!Sample_instrument_model,!Sample_library_selection,!Sample_library_source,!Sample_library_strategy,!Sample_relation,!Sample_supplementary_file_1,!series_matrix_table_begin,ID_REF,!series_matrix_table_end
S000001,GSM6103030,Public on May 09 2022,May 04 2022,May 09 2022,SRA,1,Primary breast tumor,Homo sapiens,scanb external id: Q009061.C009086.S000001.l.r...,age at diagnosis: 85,...,0,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,Reanalysis of: GSM2530698,NONE,NaN,GSM6103030,NaN
S000002,GSM6103031,Public on May 09 2022,May 04 2022,May 09 2022,SRA,1,Primary breast tumor,Homo sapiens,scanb external id: Q009043.C009085.S000002.l.r...,age at diagnosis: 66,...,0,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,Reanalysis of: GSM2530699,NONE,NaN,GSM6103031,NaN

In [4]:
# make row 0 as the column name
metadata_hiseq_copy = metadata_hiseq.copy()
metadata_hiseq_copy.columns = metadata_hiseq_copy.iloc[0]

# exclude row 0 (duplicate of the column name)
metadata_hiseq_copy = metadata_hiseq_copy.iloc[1:,:]
metadata_hiseq_copy.head(3)

!Sample_title,!Sample_geo_accession,!Sample_status,!Sample_submission_date,!Sample_last_update_date,!Sample_type,!Sample_channel_count,!Sample_source_name_ch1,!Sample_organism_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,...,!Sample_data_row_count,!Sample_instrument_model,!Sample_library_selection,!Sample_library_source,!Sample_library_strategy,!Sample_relation,!Sample_supplementary_file_1,!series_matrix_table_begin,ID_REF,!series_matrix_table_end
S000001,GSM6103030,Public on May 09 2022,May 04 2022,May 09 2022,SRA,1,Primary breast tumor,Homo sapiens,scanb external id: Q009061.C009086.S000001.l.r...,age at diagnosis: 85,...,0,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,Reanalysis of: GSM2530698,NONE,NaN,GSM6103030,NaN
S000002,GSM6103031,Public on May 09 2022,May 04 2022,May 09 2022,SRA,1,Primary breast tumor,Homo sapiens,scanb external id: Q009043.C009085.S000002.l.r...,age at diagnosis: 66,...,0,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,Reanalysis of: GSM2530699,NONE,NaN,GSM6103031,NaN
S000003,GSM6103032,Public on May 09 2022,May 04 2022,May 09 2022,SRA,1,Primary breast tumor,Homo sapiens,scanb external id: Q009039.C009084.S000003.l.r...,age at diagnosis: 63,...,0,Illumina HiSeq 2000,cDNA,transcriptomic,RNA-Seq,Reanalysis of: GSM2530710,NONE,NaN,GSM6103032,NaN

In [5]:
# extract patient characteristics columns
hiseq_patient_char = metadata_hiseq_copy.loc[:, ['!Sample_characteristics_ch1']]
hiseq_patient_char.head(3)

!Sample_title,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,...,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1
S000001,scanb external id: Q009061.C009086.S000001.l.r...,age at diagnosis: 85,tumor size: 13,lymph node group: N0,lymph node status: NodeNegative,er status: 1,pgr status: 1,her2 status: 0,ki67 status: NA,nhg: G2,...,endocrine treated: 1,chemo treated: 0,overall survival days: 3187,overall survival years: 8.72553045859001,overall survival event: 0,relapse free interval days: 387,relapse free interval years: 1.05954825462012,relapse free interval event: 0,esr1 expression: log2(tpm+0.1): 8.39647299559343,esr2 expression: log2(tpm+0.1): -3.32192809488736
S000002,scanb external id: Q009043.C009085.S000002.l.r...,age at diagnosis: 66,tumor size: 16,lymph node group: N0,lymph node status: NodeNegative,er status: 0,pgr status: 0,her2 status: 0,ki67 status: NA,nhg: G3,...,endocrine treated: 0,chemo treated: 1,overall survival days: 3192,overall survival years: 8.73921971252567,overall survival event: 0,relapse free interval days: 413,relapse free interval years: 1.13073237508556,relapse free interval event: 0,esr1 expression: log2(tpm+0.1): 3.9136724811194,esr2 expression: log2(tpm+0.1): -3.32192809488736
S000003,scanb external id: Q009039.C009084.S000003.l.r...,age at diagnosis: 63,tumor size: 32,lymph node group: N3,lymph node status: 4toX,er status: NA,pgr status: NA,her2 status: NA,ki67 status: NA,nhg: G2,...,endocrine treated: 0,chemo treated: 0,overall survival days: 785,overall survival years: 2.1492128678987,overall survival event: 1,relapse free interval days: 719,relapse free interval years: 1.96851471594798,relapse free interval event: 0,esr1 expression: log2(tpm+0.1): 3.22621375744028,esr2 expression: log2(tpm+0.1): -2.58188416103089

In [6]:
# extract survival days, years and events that are in columns 15, 16 and 17
hiseq_survival = hiseq_patient_char.iloc[:,[15, 16, 17]]
hiseq_survival.head(3)

!Sample_title,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1
S000001,overall survival days: 3187,overall survival years: 8.72553045859001,overall survival event: 0
S000002,overall survival days: 3192,overall survival years: 8.73921971252567,overall survival event: 0
S000003,overall survival days: 785,overall survival years: 2.1492128678987,overall survival event: 1

In [7]:
# rename column names
hiseq_survival.columns = ['overall_survival_days', 'overall_survival_years', 'overall_survival_event']
hiseq_survival.head(3)

,overall_survival_days,overall_survival_years,overall_survival_event
S000001,overall survival days: 3187,overall survival years: 8.72553045859001,overall survival event: 0
S000002,overall survival days: 3192,overall survival years: 8.73921971252567,overall survival event: 0
S000003,overall survival days: 785,overall survival years: 2.1492128678987,overall survival event: 1

### 2. Convert survival data into suitable format

In [8]:
# function to keep only numbers in the survival data
def keep_numbers_in_survival(df, col_names):
    df_copy = df.copy()
    df_nrow = df_copy.shape[0]
    for col in col_names:
        for i in range(df_nrow):
            value = df_copy.loc[df_copy.index[i], col]
            df_copy.loc[df_copy.index[i], col] = value.split(': ')[1]

    return df_copy

In [9]:
# keep only the numeric data
hiseq_survival_modified = keep_numbers_in_survival(hiseq_survival, hiseq_survival.columns.tolist())
hiseq_survival_modified.head(3)

        overall_survival_days overall_survival_years overall_survival_event
S000001                  3187       8.72553045859001                      0
S000002                  3192       8.73921971252567                      0
S000003                   785        2.1492128678987                      1

In [10]:
# convert data types
hiseq_survival_modified['overall_survival_event'] = pd.to_numeric(hiseq_survival_modified['overall_survival_event'], errors ='coerce').astype('Int64')
hiseq_survival_modified['overall_survival_days'] = pd.to_numeric(hiseq_survival_modified['overall_survival_days'], errors ='coerce').astype('Int64')
hiseq_survival_modified['overall_survival_years'] = pd.to_numeric(hiseq_survival_modified['overall_survival_years'], errors ='coerce').astype('Float64')

In [11]:
hiseq_survival_modified.head(3)

         overall_survival_days  overall_survival_years  overall_survival_event
S000001                   3187                 8.72553                       0
S000002                   3192                 8.73922                       0
S000003                    785                2.149213                       1

In [12]:
# check data types
hiseq_survival_modified.dtypes

overall_survival_days       Int64
overall_survival_years    Float64
overall_survival_event      Int64
dtype: object

In [13]:
# check the proportion of survival events
hiseq_survival_modified['overall_survival_event'].value_counts()

overall_survival_event
0    2486
1     426
Name: count, dtype: Int64

In [14]:
# check for missing values
hiseq_survival_modified.isna().sum(axis=0)

overall_survival_days     1
overall_survival_years    1
overall_survival_event    1
dtype: int64

In [15]:
# check which samples (rows) have missing values
hiseq_survival_modified.loc[hiseq_survival_modified.isna().any(axis=1),:]

         overall_survival_days  overall_survival_years  overall_survival_event
S000988                   <NA>                    <NA>                    <NA>

In [16]:
# remove the sample with missing survival data
hiseq_survival_modified = hiseq_survival_modified.loc[~hiseq_survival_modified.isna().any(axis=1),:]
hiseq_survival_modified.shape

(2912, 3)

In [17]:
# round the overall_survival_years to 3 decimal places
hiseq_survival_modified.loc[:,'overall_survival_years'] = round(hiseq_survival_modified['overall_survival_years'],3)
hiseq_survival_modified.head(3)

         overall_survival_days  overall_survival_years  overall_survival_event
S000001                   3187                   8.726                       0
S000002                   3192                   8.739                       0
S000003                    785                   2.149                       1

In [18]:
# check the maximum overall survival years in the whole hiseq dataset (including unclassified and normal-like samples)
hiseq_survival_modified.loc[hiseq_survival_modified['overall_survival_years'].idxmax(),'overall_survival_years']

8.739

### 3. Split survival data according to SCAN-B HiSeq training and test sets

In [19]:
# import scanb hiseq training and test data
scanb_hiseq_train = pd.read_csv("C:/Users/User/Documents/master_thesis_project_analysis/datasets/SCANB_GSE202203/scanb_hiseq_train_test_sets/train_test_80_20/SCANB_HiSeq_pam50gene_raw_counts_subtype_train_80.csv", 
                          header=0, index_col=0)

scanb_hiseq_test = pd.read_csv("C:/Users/User/Documents/master_thesis_project_analysis/datasets/SCANB_GSE202203/scanb_hiseq_train_test_sets/train_test_80_20/SCANB_HiSeq_pam50gene_raw_counts_subtype_test_20.csv", 
                          header=0, index_col=0)

In [20]:
print(scanb_hiseq_train.shape)
print(scanb_hiseq_test.shape)

(2204, 52)
(551, 52)

In [21]:
# check whether the sample with missing survival is in the training or test set
print('True') if 'S000988' in scanb_hiseq_train.index else print('False')
print('True') if 'S000988' in scanb_hiseq_test.index else print('False')

True
False

In [22]:
# check the subtype label of the sample with missing survival data
# remove this sample during survival analysis
scanb_hiseq_train.loc['S000988','subtype']

'LumB'

In [23]:
# extract survival data of training and test sets
hiseq_survival_train = hiseq_survival_modified.loc[hiseq_survival_modified.index.isin(scanb_hiseq_train.index),:]
hiseq_survival_test = hiseq_survival_modified.loc[hiseq_survival_modified.index.isin(scanb_hiseq_test.index),:]
print(hiseq_survival_train.shape)
print(hiseq_survival_test.shape)

(2203, 3)
(551, 3)

In [24]:
# get the maximum survival years in the training and test sets
print(hiseq_survival_train.loc[hiseq_survival_train['overall_survival_years'].idxmax(),'overall_survival_years'])
print(hiseq_survival_test.loc[hiseq_survival_test['overall_survival_years'].idxmax(),'overall_survival_years'])

8.739
8.736

In [25]:
# check the proportion of survival events in training and test sets
print('Training set:')
print(hiseq_survival_train['overall_survival_event'].value_counts())

print('\nTest set:')
print(hiseq_survival_test['overall_survival_event'].value_counts())

Training set:
overall_survival_event
0    1870
1     333
Name: count, dtype: Int64

Test set:
overall_survival_event
0    475
1     76
Name: count, dtype: Int64

In [26]:
# select only the rows from gene expression_subtype dataset that are in survival dataset
# reorder the rows in the gene expression_subtype dataset according to the survival dataset
# note: the sample with missing survival data is in the training dataset, and is removed
scanb_hiseq_train_sorted = scanb_hiseq_train.loc[hiseq_survival_train.index,:]
scanb_hiseq_test_sorted = scanb_hiseq_test.loc[hiseq_survival_test.index,:]
print(scanb_hiseq_train_sorted.shape)
print(scanb_hiseq_test_sorted.shape)

# check whether the indices match
print(scanb_hiseq_train_sorted.index.equals(hiseq_survival_train.index))
print(scanb_hiseq_test_sorted.index.equals(hiseq_survival_test.index))

(2203, 52)
(551, 52)
True
True

### 4. Merge survival data with subtype labels

In [27]:
# merge survival and subtype data
hiseq_train_survival_subtype = hiseq_survival_train.join(scanb_hiseq_train_sorted.loc[:,'subtype'])
hiseq_test_survival_subtype = hiseq_survival_test.join(scanb_hiseq_test_sorted.loc[:,'subtype'])
print(hiseq_train_survival_subtype.shape)
print(hiseq_test_survival_subtype.shape)

(2203, 4)
(551, 4)

In [36]:
# # save file
# hiseq_train_survival_subtype.to_csv('scanb_hiseq_train_survival_subtype.csv')
# hiseq_test_survival_subtype.to_csv('scanb_hiseq_test_survival_subtype.csv')